# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0002_game_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_score',
            field=models.FloatField(),
        ),
    ]
